//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietNha
    {
        public int MaNha { get; set; }
        public Nullable<int> DienTich { get; set; }
        public Nullable<int> SoPhong { get; set; }
    
        public virtual Nha Nha { get; set; }
    }
}
