//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietMuaThue
    {
        public int Id { get; set; }
        public Nullable<int> MaMuaThue { get; set; }
        public Nullable<int> MaNha { get; set; }
        public string LoaiGiaoDich { get; set; }
        public Nullable<int> SoNamThue { get; set; }
        public Nullable<int> MaGia { get; set; }
        public Nullable<decimal> Gia { get; set; }
    
        public virtual GiaNha GiaNha { get; set; }
        public virtual MuaThueNha MuaThueNha { get; set; }
        public virtual Nha Nha { get; set; }
    }
}
