//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nha
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nha()
        {
            this.ChiTietMuaThues = new HashSet<ChiTietMuaThue>();
            this.GiaNhas = new HashSet<GiaNha>();
        }
    
        public int MaNha { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public Nullable<int> MaXa { get; set; }
        public Nullable<int> MaHuyen { get; set; }
        public Nullable<int> MaTinh { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietMuaThue> ChiTietMuaThues { get; set; }
        public virtual ChiTietNha ChiTietNha { get; set; }
        public virtual District District { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiaNha> GiaNhas { get; set; }
        public virtual LoaiNha LoaiNha { get; set; }
        public virtual Province Province { get; set; }
        public virtual Ward Ward { get; set; }
        public virtual TrangThaiNha TrangThaiNha { get; set; }
    }
}
